### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by awafaa** [jangouts/jangouts#110]
When I browse to my instance I am unable to sign in , I have tried from Firefox on Linux and OSX as well as Chrome on OSX and Android. I only see an error when using Firefox which is:

<code>Janus error: error: [Exception... "<no message>"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: https://jangouts.wafaa.eu/scripts/vendor-f4c09c8a.js :: .send :: line 27"  data: no]
Do you want to reload in order to retry?</code>

Chrome shows no error but when I select the sign in button nothing happens.

I'm not sure if this is related to issue #109 or not.

**Comment by ancorgs** [comment]
That looks like a Janus crash. You should inspect the janus logs with
```
journalctl -u janus.service
```
Or even better watching when the error happens using
```
journalctl -f -u janus.service
```

**Comment by awafaa** [comment]
So nothing actually shows up in the janus logs when I access the server from either Chrome or Firefox :disappointed: 

```bash
systemctl status -l janus.service
janus.service - Janus WebRTC Gateway
   Loaded: loaded (/usr/lib/systemd/system/janus.service; enabled)
   Active: active (running) since Sat 2015-12-19 08:29:25 GMT; 24s ago
 Main PID: 19033 (janus)
   CGroup: /system.slice/janus.service
           └─19033 /usr/bin/janus

Dec 19 08:29:25 fveusrv01 janus[19033]: JANUS WebSockets transport plugin initialized!
Dec 19 08:29:25 fveusrv01 janus[19033]: Loading transport plugin 'libjanus_http.so'...
Dec 19 08:29:25 fveusrv01 janus[19033]: WebSocket (Janus API) thread started
Dec 19 08:29:25 fveusrv01 janus[19033]: HTTP webserver started (port 8088, /janus path listener)...
Dec 19 08:29:25 fveusrv01 janus[19033]: [WARN] HTTPS webserver disabled
Dec 19 08:29:25 fveusrv01 janus[19033]: [WARN] Admin/monitor HTTP webserver disabled
Dec 19 08:29:25 fveusrv01 janus[19033]: [WARN] Admin/monitor HTTPS webserver disabled
Dec 19 08:29:25 fveusrv01 janus[19033]: JANUS REST (HTTP/HTTPS) transport plugin initialized!
Dec 19 08:29:25 fveusrv01 janus[19033]: Sessions watchdog started
Dec 19 08:29:25 fveusrv01 janus[19033]: HTTP/Janus sessions watchdog started
```
I'm building on Tumbleweed, but just realised that my server is running a rather crusty old 13.1. Would that be a contributing factor?

**Comment by ancorgs** [comment]
So you are not reaching the janus server. I googled that "[Exception... "" nsresult: "0x805e0006" error and indeed it seems to be a (rather cryptic) jQuery error meaning that an ajax call failed to reach the resource.

Not sure if it will help in this particular case, but in order to better debug the javascript, it would be better to comment this line https://github.com/jangouts/jangouts/blob/master/gulp/build.js#L46 and run `gulp build` again. At least, this way browser errors will point to meaningful lines.

**Comment by awafaa** [comment]
So I commented out line 46 and I now get:
```bash
Janus error: error: [Exception... "<no message>"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: https://jangouts.wafaa.eu/scripts/vendor-f4c09c8a.js :: .send :: line 8561"  data: no]
Do you want to reload in order to retry?
```
Again only Firefox shows the error, Chrome shows no errors but does nothing.

**Comment by awafaa** [comment]
Just retried with a fresh checkout using v0.4.1 and finally Chrome spits out an error:
```bash
Janus error: Error connecting to any of the provided Janus servers: Is the gateway down?
Do you want to reload in order to retry?
```
Problem is the gateway is up, at least according to systemctl; and reloading does nothing other than spit the same error message back:
```bash
systemctl status janus.service 
janus.service - Janus WebRTC Gateway
   Loaded: loaded (/usr/lib/systemd/system/janus.service; enabled)
   Active: active (running) since Sat 2015-12-19 08:29:25 GMT; 3 days ago
 Main PID: 19033 (janus)
   CGroup: /system.slice/janus.service
           └─19033 /usr/bin/janus
```

The same error is reported by Opera & Firefox.

**Comment by imobach** [comment]
Hi @awafaa,

Version 0.4.1 is discouraged as contains a critical bug when reading the configuration. We've created an installation guide for [openSUSE/SLE](https://github.com/jangouts/jangouts/wiki/openSUSE-SLE). Maybe you'd like to give it a try.

Feel free to reopen this issue (or submit a new one) if it does not help.

Thanks!
