### ISSUE TITLE
Configure without rebuilding

### ISSUE THREAD

**Issue by ancorgs** [jangouts/jangouts#111]
We need another configuration method that doesn't imply running gulp and repackaging everything. Thus, we can provide for download already compiled versions that can be just be dropped in the apache server, without the node, bower and gulp hassle.

**Comment by imobach** [comment]
For me the best approach is adding a `dist/`directory in the repository.

**Comment by imobach** [comment]
BTW, we could also create an RPM with Apache/Nginx configuration included.

**Comment by lnussel** [comment]
maybe consider putting the built version in a branch. diffs from autogenerated files just suck.

**Comment by imobach** [comment]
As suggested by @lnussel we're using another branch (called `releases`) and using the release mechanism provided by Github. We've released version 0.4.1 in that way so I'm closing this issue.
