### ISSUE TITLE
PIN code room

### ISSUE THREAD

**Issue by nlienard** [jangouts/jangouts#130]
Hi

I'm using Janus as gateway, and it works perfectly with Jangouts (and thanks for that).

Now; i got a test room configured with a PIN:

[12341]
description = pin test
pin = 12345
publishers = 6
bitrate = 128000
fir_freq = 10
record = false

When trying to go to this room through Jangouts; there is a popup with following message : 

Missing element (pin)

Is there any way to implement the PIN code access into room ?

Thanks a lot !

**Comment by code-master5** [comment]
@ancorgs I want to work on this. Can you please guide me a bit on this???

**Comment by ancorgs** [comment]
Fixed by #182
