### ISSUE TITLE
sent text doesn't always clear in chat window

### ISSUE THREAD

**Issue by aspiers** [jangouts/jangouts#132]
After I send a chat message and hit `Enter` or click `Send`, whatever I typed always persisted in the `Type your message here` area.  After reloading the Jangouts window, this stopped happening.

**Comment by ancorgs** [comment]
That happened because the data channel got broken, so the message cannot be sent. That's the expected behavior in such situation.

**Comment by aspiers** [comment]
Thanks, but in that case there are two issues:

1. After pressing `Send`, the message should not appear in the chat part of the window.  Currently it does, which makes it look like it got sent, and that's highly confusing.
2. If the message can't be sent, the UI should explain this rather than just mysteriously disabling sending.

So this really needs reopening.
