### ISSUE TITLE
Allow name change

### ISSUE THREAD

**Issue by ancorgs** [jangouts/jangouts#15]
Allow the users to change their name during the session

**Comment by ancorgs** [comment]
This will become more relevant when we finish some changes currently under implementation, that will lead to remembered (cookie based) user name.

**Comment by PaliwalSparsh** [comment]
@ancorgs I want to work on this bug please can you help on how to get started with it I have built jangouts successfully. jh-feed.html is where we can find the element. Please can you direct to what i need to read to work on this.

**Comment by ancorgs** [comment]
@PaliwalSparsh actually, `jh-feed.html`is where the name is displayed, but there is nothing you need to change there. It will be updated automagically if the name of the underlying feed is changed.

Every feed is represented by an instance of `FeedFactory`. What you need to do is:

- Provide a mechanism for users to update the attribute `display` of the main feed (which is the one representing themselves).
- Make sure that the function implemented to change `display` calls `DataChannelService.sendStatus(that)` so other participants notice the change.
- (bonus track) Update the url displayed in the browser, since it displays the username
- (extra bonus track) Provide a nice transition for the redrawing of the list of participants, it will get reorganized in the change introduces an alteration in the alphabetical order.

**Comment by ancorgs** [comment]
As an inspiration for such a function, just take a look to `updateLocalPic`, for example.

**Comment by code-master5** [comment]
@ancorgs @imobachgs I'm working on this.

**Comment by ancorgs** [comment]
Fixed by #183
