### ISSUE TITLE
Community communication channel

### ISSUE THREAD

**Issue by ancorgs** [jangouts/jangouts#153]
Jangouts development has worked so far in a impulse-driven way. We get contributions and contributors in every Hack Week, pre-GSoC, GSoC itself... But even if we have had contributions from more than 10 people in one way or another, I feel we still lack a community common vision.

There are several topics I would like to discuss with everybody interested in Jangouts. The days of @imobachgs and myself deciding on the project direction in our small office should be over. So the first question is what should be the channel for discussing those topics.

Some projects simply use issues in Github for that kind of conversations. I'm not sure I like that.

Many other projects, including Janus Gateway, use Google Groups for open general discussion (even support), keeping Github issues just for more concrete bug reports and fate requests.

Last but not least, since openSUSE already acted as some kind of patron giving us one slot for GSoC, we could maybe give another step in that direction and ask openSUSE for a mailing list jangouts@opensuse.org.

What alternative do you prefer? Any other option?

**Comment by jreidinger** [comment]
Any mailing list is fine for me. Even github issues is something I can live with, if it comes with some kind of road map, where we wanna go and what should be included and what not.

**Comment by bmwiedemann** [comment]
We could also look at https://www.fossil-scm.org/xfer/doc/trunk/www/foss-cklist.wiki or http://spot.livejournal.com/308370.html for points we might be lacking for good open-source projects.

Overall, I would prefer a ML on a neutral domain (e.g. devel@jangouts.org) over a openSUSE one, to not give the impression, that it only works on openSUSE or should be driven mostly by openSUSE people.

**Comment by aspiers** [comment]
+1 on avoiding opensuse.org, since I think this would deter some people outside the openSUSE community. I think Google Groups is a pretty good option - low maintenance, neutral, good for sane people who like mailing lists and also for totally crazy people who prefer web forums ;-)

Also +1 for keeping the github issue tracker. I like the precision that that can bring to even architectural / mission discussions. Mailing list threads can sometimes go off on tangents too easily (although that's fine as long as people remember to change the Subject header ...)

**Comment by uhelp** [comment]
+1 for avoiding opensuse.org and using jangouts.org

I  prefer jangouts.org instead feeding data trolls like google

**Comment by ancorgs** [comment]
@uhelp What's your suggestion for the technical part of jangouts.org? Buying the domain is the easy part. But if you don't want to feed data trolls I guess you are suggesting to host our own mailing list software on our own server. Or do you have any alternative in mind that is as straightforward as Groups  from the setup/maintenance point of view?

**Comment by lnussel** [comment]
Bullshit about opensuse.org. Show some pride! Would be a really
nice. Quite some projects are hosted by fedora or debian and noone
bothers. I'd avoid opensuse.org just for the antiquated mailinglist
software and archive there.

Google groups is nice to interface with non techies as it looks like
a web forum to them but is actually a mailinglist.

**Comment by uhelp** [comment]
Yes, I'd prefer running all of it on a root server.
Some docker containers and things are easily moveable/upgradable
.
Jangouts should also run on different distris, so tutorials for other distris and setup howtos are needed as well. Some nginx container, a framework for CMS should do the trick. 
And of course a demo site as well.

Hence pride may be the wrong term here.
Nothing prevents to credit openSUSE on the jangout site.

**Comment by magarcia** [comment]
+1 to Google Groups, like @lnussel says is actually a mailing list, and a lot of project use it so non tech users and tech people that no contribute normally to open source projects are more accustomed to use it.
If we want to get more contribution to the project, IMHO this solution will be useful for a bigger range of people.

**Comment by bmwiedemann** [comment]
Just in case someone needs it, there is now http://jangouts.org/cgi-bin/mailman/listinfo/devel available.
And then there was the question about the overlap with jitsi which is also opensource videophony and seems to be a rather active and mature project. Did anyone try it? Can we do things they cannot?

**Comment by cyntss** [comment]
I like the idea of using Google Groups. Mailing lists already take a big part of my day and I would not like to overload it. I never used Google Groups, but I saw it in some projects and the fact that it looks like a forum would make it easy to catch up when threads get very big, plus it's more organised from a UX point of view :)

Github issues are also a good option to me. So, either Google Groups or Github Issues, they both look like good ideas.

What is important to me is what @jreidinger mentioned in his comment: having and preparing some sort of road map with milestones, and how we could decide on where to go, voting on issues perhaps? or do we program/design upon what we think is best for the project?

**Comment by imobachgs** [comment]
@bmwiedemann Thanks for setting up a mailing list! I'm fine with using it (but I'm also not against Google Groups, although I'm not a big fan). I would use the ML for community communication and general discussion and Github issues for specific development code and bug reporting (they look like complementary to me).

My 2 cents.

PS: I agree that we urgently need some kind of vision/roadmap for the future.

**Comment by imobachgs** [comment]
About the rest of the infrastructure, currently we have a demo server at https://jangouts.tk/. Unfortunately we're missing proper documentation.

Regarding the Docker instances I'll be happy to share them, for example, in Docker Hub. But we need some manpower to create, maintain and document them. I'm quite interested in Docker and I could try to do it but if we have some expert onboard... :)

**Comment by ancorgs** [comment]
Ok. So looks like everybody likes the combination of
 - Github issues to track feature requests
 - a non-openSUSE mailing list

The only point that is not crystal clear from the discussion is whether that list should be Google Groups or a self-hosted mailman.

For me, the self hosted solution is only an option if we have at least two volunteers that can sign with blood that they will administer that service for at least one year. Otherwise, I prefer the almost-zero setup and zero maintenance solution (Google Groups).

If we don't have such volunteers, the decision is made. If they step up, I will create a poll to decide between both possibilities.

**Comment by ancorgs** [comment]
To speed up things, no need to wait for the volunteers to pop-up in order to start voting. So...

+1 to this comment (using the "add your reaction" button in Github) if you prefer Google Groups.

-1 to this comment if you prefer the self-hosted mailman (assuming we have volunteers to maintain the service).

**Comment by ancorgs** [comment]
@bmwiedemann @aspiers @lnussel @cyntss Any vote? (see previous comments)

**Comment by aspiers** [comment]
I don't mind either way, so I'm abstaining.

**Comment by cyntss** [comment]
Vote given 👍

**Comment by ancorgs** [comment]
So we have a winner. I will create a Google group today or tomorrow. Thanks all.

**Comment by ancorgs** [comment]
Done. Here is the group url https://groups.google.com/forum/#!forum/jangouts and here are the instructions to join https://support.google.com/groups/answer/1067205?hl=en

**Comment by ancorgs** [comment]
I just realized the good & old mailing-list style way of joining is not described in that document.

Just send a mail to jangouts+subscribe@googlegroups.com

It simply works.
