### ISSUE TITLE
Possibility to silently join and monitor rooms

### ISSUE THREAD

**Issue by aaannz** [jangouts/jangouts#158]
When there is no video and audio input device, or sharing of them is denied in FF, Jangouts still allows participant to join.
His/her presence is however not displayed (not even joining message is present) to other participants, his/hers messages are not distributed to others and, obviously, no one can hear or see him/her.
This participant however can see, hear and read messages of other participants.

This has a potential to be misused for unauthorized information gathering. Tested in FF 48.0.2, 49.0.1, 51.a2 (Devel edition)

**Comment by bedi1982** [comment]
Hello, I can confirm this bug as I just 'trigger' it.

**Comment by ancorgs** [comment]
First of all, take into account Jangouts is not designed to be super-secure. I mean, Jangouts is "just" a Janus client. Any Janus client (and it's trivial to implement or download one) can have access to the WebRTC traffic. Securizing the WebRTC traffic is out of Jangouts scope.

That been said. It's true there is a lot of room for improvements to raise the awareness about "lurkers". For example, we could compare the number of people subscribed to your stream and the number of publishers. If numbers do not match, there is somebody listening but not being displayed. That's something we could show in the UI.

**Comment by ancorgs** [comment]
As can be seen [in this conversation](https://groups.google.com/d/topic/meetecho-janus/LxYDHUAk_7E/discussion), this is not as easy as expected. It implies implementing some kind of authentication (at least enforcing that everybody that connects to a room to know a shared secret) or implementing a new mode in the videoroom Janus plugin.

None of the solutions are 100% satisfactory to our use-case. So I will let this rest a bit.

**Comment by ancorgs** [comment]
Good news in this regard. Around one year ago, Janus Gateway [added the possibility](https://github.com/meetecho/janus-gateway/commit/152c7e5da0c3bf9bf20ec3e12b77fb2008555427) of configuring rooms with a new parameter that makes it possible to detect users that are in the room but not transmitting any video/audio stream.

Now we are implementing compatibility with that in Jangouts, so #337 should mark the end of the era of the lurkers.

**Comment by ancorgs** [comment]
#337 is merged, so I'm closing this. I expect to release a new version of Jangouts including the fix next week (and I will try to make sure it's deployed in jangouts.suse.de).

**Comment by ancorgs** [comment]
> #337 is merged, so I'm closing this. I expect to release a new version of Jangouts including the fix next week (and I will try to make sure it's deployed in jangouts.suse.de).

I deployed 0.5.0 in jangouts.suse.de and configured the rooms to notify all participants. Everybody should be immediately visible as they join now, even if they do not share their camera/mic.
