### ISSUE TITLE
Low Video Quality

### ISSUE THREAD

**Issue by manno** [jangouts/jangouts#159]
The streams video quality is very low. Webcam streams as well as screen sharing suffer from compression artifact. To read text, the picture has to 'rest' for about 2 seconds, before the codec is able to sharpen the image. Maybe the bitrate of the video streams is too low?

**Comment by ancorgs** [comment]
The bitrate of the video is set separately for each room in the Janus configuration (server side). Setting it to a high limit should kill all artifacts.

**Comment by ancorgs** [comment]
Not a Jangouts issue, I would say. Looks like a configuration issue in the instance to me.
