### ISSUE TITLE
"Has left the room" message displayed twice

### ISSUE THREAD

**Issue by ancorgs** [jangouts/jangouts#171]
When the user OneUser quits, the other participants see the message "OneUser has left the room" twice. That should not be the case.

**Comment by anweshknayak** [comment]
@ancorgs It's working fine on firefox. ?

**Comment by code-master5** [comment]
@ancorgs @imobachgs As we can see in src/app/components/room/room.service.js
`           else if (event === "event") {
            // Any new feed to attach to?
            if ((msg.publishers instanceof Array) && msg.publishers.length > 0) {
              that.subscribeToFeeds(msg.publishers, that.room.id);
            // One of the publishers has gone away?
            } else if(msg.leaving !== undefined && msg.leaving !== null) {
              var leaving = msg.leaving;
              ActionService.destroyFeed(leaving);
            // One of the publishers has unpublished?
            } else if(msg.unpublished !== undefined && msg.unpublished !== null) {
              var unpublished = msg.unpublished;
              ActionService.destroyFeed(unpublished);
            // Reply to a configure request
            } else if (msg.configured) {
              connection.confirmConfig();
            // The server reported an error
            } else if(msg.error !== undefined && msg.error !== null) {
              console.log("Error message from server" + msg.error);
              $$rootScope.$broadcast('room.error', msg.error);
}`

**Comment by ancorgs** [comment]
Fixed by #181
