### ISSUE TITLE
404 Not Found - vm.feed.getPicture()

### ISSUE THREAD

**Issue by ancorgs** [jangouts/jangouts#172]
When jangouts load, it displays the following error in the javascript console

```
"NetworkError: 404 Not Found - https://jangouts.suse.de/%7B%7Bvm.feed.getPicture()%7D%7D"
```

And sometimes the browser icon keeps spinning because it's actually trying to reach that location with no success.

Obviously, the URL does not exists and such http request should not happen.

**Comment by imobachgs** [comment]
This issue should be fixed by #175.
