### ISSUE TITLE
Gulp watch 

### ISSUE THREAD

**Issue by anweshknayak** [jangouts/jangouts#173]
Implementing a gulp watch task to oversee any current changes in static files

**Comment by code-master5** [comment]
@ancorgs I'm working on this!

**Comment by imobachgs** [comment]
@anweshknayak Thanks for your suggestion. Such a feature would be nice, but for the angular-2 version we are dropping gulp and I am not sure if anyone is willing to implement this for master.

So, I am sorry, but I will close this one. Please, feel free to open a PR ;)
