### ISSUE TITLE
error during installation of angular2 branch

### ISSUE THREAD

**Issue by nikhilrayaprolu** [jangouts/jangouts#176]
I am facing this issue on installing typings for the angular2  branch.
![image](https://cloud.githubusercontent.com/assets/15216503/23586492/d0e8a5a0-01bb-11e7-9f6b-6822a4d056db.png)

I am interested in contributing to jangouts as a part of GSOC 2017 .

**Comment by nikhilrayaprolu** [comment]
I would also want to know if you are interested in using angular-cli for the angular2 branch . since angular-cli would have a good support and a standard way for installation.

**Comment by imobachgs** [comment]
It looks like a SSL problem. Are you behind a firewall? Does the following command work for you (check the _Verify return code_)?

```
openssl s_client -connect api.typings.org:443 -ssl3
```

Anyway, I guess you could disable https and use http instead by just creating a `.typingsrc` including this configuration option:

```
registryURL=http://api.typings.org/
```

Could you give it a try?

**Comment by nikhilrayaprolu** [comment]
thank you @imobachgs . i am able to run jangouts now .
Can I know if there are any bugs that needed to be solved in the angular2 branch .(I couldn't distinguish which issues are related to angular2 branch.

**Comment by nikhilrayaprolu** [comment]
secondly do you want GSOC aspirants to work on their project ideas for main branch or for angular-2 branch?

**Comment by imobachgs** [comment]
`angular-2` branch is still a WIP and we would like to do some important changes before the GSoC starts. So you can focus in the `master` branch except if you plan to work on 
https://github.com/openSUSE/mentoring/issues/77 which is intended to be implemented in the `angular-2` branch only.

**Comment by imobachgs** [comment]
And about bugs to solve, all of them apply to the `master` branch: https://github.com/jangouts/jangouts/issues?q=is%3Aissue+is%3Aopen+label%3A%22junior+job%22

Thanks!
