### ISSUE TITLE
Integrate latest Janus-gateway with the master branch

### ISSUE THREAD

**Issue by code-master5** [jangouts/jangouts#187]
I think doing this is important, mainly because:
    1. For adding Pin Code Room functionality. Janus-gateway added the required feature here (https://github.com/meetecho/janus-gateway/commit/cabe80ea35c76b36d3180b4f7063d60fa728548d). The PR #182 is waiting for this, to get merged.
    2. For integrating with callstats.io we need latest Janus-gateway (to accomodate new changes in Janus-gateway to be carried out in future in this regard).

I've already started working on this.

**Comment by ancorgs** [comment]
Fixed by #193
