### ISSUE TITLE
can not hear or see other people in the room but icons show up

### ISSUE THREAD

**Issue by okurz** [jangouts/jangouts#189]
Similar to #184 and #174 and #158: I can see the icons of people in the room but can neither see them, nor hear them nor see their text messages. A "workaround" that worked for other issues (ignore/un-ignore) did not help here. One person out of 8 showed up and I was able to hear and see him. One other person then was suddenly audible and visible after about 10 minutes in the call.

**Comment by okurz** [comment]
potential workaround for VPN users: Use different VPN gateway and/or MTU size

**Comment by ancorgs** [comment]
@okurz Any concrete advise regarding MTU size?

**Comment by okurz** [comment]
On Tuesday, 2 May 2017 07:43:43 CEST Ancor Gonzalez Sosa wrote:
> @okurz Any concrete advise regarding MTU size?

no ideas. I just heard rumors but no definite values

**Comment by okurz** [comment]
It seems to be related to the use of VPN. Yesterday in office it worked for me. Now from home over gate.suse.de no joy at all.

**Comment by ancorgs** [comment]
Yes, all the connection problems with the internal SUSE instance are always related to VPN. Not sure if we (the Jangouts maintainers) can do much regarding that. We hope future integration with callstats.io will help the network admin to not break WebRTC traffic when adjusting VPN and other network stuff.

**Comment by ancorgs** [comment]
That been said. Using the TCP VPN instead of the UDP-based one is helping us a lot this week. Please try as a temporary workaround. The results are usually different with every one of the 4 combinations UDP/TCP and PRG/NUE.

**Comment by okurz** [comment]
It might be that the issue is triggered by an unstable network but IMHO jangouts should provide better user feedback. For example: If I am alone in the room (for testing) I can't see if that problem is there, right? Also, when it happens one realizes when he can't see/hear others but not really understand what the issue is. You can call it a feature request for UI improvement.

**Comment by okurz** [comment]
New symptoms: I connect, icons of people already in the room show up, can't hear or see them or their chat messages. I see and hear people joining after me (or reconnecting/rejoining while I am in the room). What worked though is that I stayed within that room with firefox and in parallel connected with chromium. Within chromium I could see and hear everyone fine.

**Comment by ancorgs** [comment]
Issues marked as "related_to_vpn" seemed to only happen in the SUSE VPN. We have never been able to reproduce them in VPN-free environments.

So I'm closing them all.

If you believe it's a general problem non related to VPN, please verify it at https://li2023-182.members.linode.com/
