### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hpanago** [jangouts/jangouts#190]
I can't seem to be able to find a correct way to install Jangouts on Debian.
Is there any documentation you can point me to?

Also when tried to do it on opensuse (systemctl start janus.service) I got the error from systemd 

"Apr 26 06:14:09 linux-qifh systemd[1]: janus.service: Main process exited, code=exited, status=1/FAILURE
Apr 26 06:14:09 linux-qifh systemd[1]: janus.service: Unit entered failed state.
Apr 26 06:14:09 linux-qifh systemd[1]: janus.service: Failed with result 'exit-code'.
Apr 26 06:14:09 linux-qifh systemd[1]: janus.service: Service hold-off time over, scheduling restart.
Apr 26 06:14:09 linux-qifh systemd[1]: Stopped Janus WebRTC Gateway.
Apr 26 06:14:09 linux-qifh systemd[1]: janus.service: Start request repeated too quickly.
Apr 26 06:14:09 linux-qifh systemd[1]: Failed to start Janus WebRTC Gateway.
Apr 26 06:14:09 linux-qifh systemd[1]: janus.service: Unit entered failed state.
Apr 26 06:14:09 linux-qifh systemd[1]: janus.service: Failed with result 'start-limit'."

Thank you.

**Comment by imobachgs** [comment]
The error message is from the [Janus](https://janus.conf.meetecho.com/) server (not Jangouts at all). I guess you're using the official Debian packages and maybe there's some problem with your configuration. You could try to check `journalctl -u janus` to see what's happening.

When you have Janus running, we can help you to set up Jangouts if needed. OTOH, it would be great if you can write some lines about installing Janus on Debian because we don't have documentation for that.

**Comment by hpanago** [comment]
This happened with the OpenSuse official package.
Debian does not have one.

In order to install jangouts on Debian it looks like that I have to install from source/github both the janus gateway and jangouts. If I can figure it out, I will let you know.

**Comment by imobachgs** [comment]
@hpanago Janus is [already packaged](https://packages.debian.org/search?keywords=janus&searchon=names&suite=all&section=all) for Sid/Experimental.

About openSUSE, we have an [installation guide](https://github.com/jangouts/jangouts/wiki/Installation-guides) for openSUSE/SLE which worked the last time I tried. And also we have our [script](https://github.com/jangouts/jangouts/blob/master/provisioning/setup.sh) to set up our development machines. 

The only problem is that they're based on openSUSE Leap 42.1 (or SUSE Enterprise Linux 12 SP1).

**Comment by mishal** [comment]
You can use AG Projects Repo to install it on Debian Jessie...

https://janus.conf.meetecho.com/docs/resources.html

**Comment by ancorgs** [comment]
Just make sure whatever package you use for whatever distro is compiled with support for data channels.

**Comment by ancorgs** [comment]
Last but not least, looks like there are at least 3 containered versions of Jangouts out there:
https://github.com/Elhodred/docker-jangouts
https://github.com/kiview/jangouts-docker
https://github.com/lmangani/docker-jangouts

So deploying with docker should be easy
