### ISSUE TITLE
"Ignoring" someone is too strong

### ISSUE THREAD

**Issue by mvidner** [jangouts/jangouts#20]
I see that to Ignore someone means turning off their
- video
- audio
- chat messages

That may be OK for an annoying person in a public chat, but our use case is cancelling echos when sitting in the same room. For that, you should definitely see the chat messages (with links to issue trackers) and possibly also the video (if the other party is sitting back to back with you).

**Comment by ancorgs** [comment]
Canceling echoes without ignoring is already possible with right click on the participant thumbnail -> mute. That will mute that participant only locally.

**Comment by ancorgs** [comment]
On the other hand, the ignore button has proven to be useful to reset the connection with a peer without quiting the room. If you are not getting audio, video or data from some concrete participant, you can ignore him and stop ignoring him immediately afterwards. That resets the three channels and has become the main use case for the ignore button. :wink:

**Comment by ancorgs** [comment]
I'm cleaning up the list of issues. As explained in the previous comment, browsers already allow "ignoring" the audio, so closing this.
