### ISSUE TITLE
Room Swap 

### ISSUE THREAD

**Issue by cshar85** [jangouts/jangouts#214]
I recently got jangouts/janus-gateway working and it is awesome with how smooth it is. Does it have the ability to hop to a different room after login and hold the username? 

is there a place i can input an html5 dropdown and or jade using a hrefs to domainname.com/dist/#/rooms/####?user=RoomInvader

Whenever i tried to input it into the footer, it doesn't seem to hold, but i may just need to rebuild dist from the app src.

Thanks!

**Comment by cshar85** [comment]
Found a simple way to do this in development with extra code.
<form>
       <fieldset>
          <legend>Rooms</legend>
          <p>
             <label>Select list</label>
             <select name="menu" onchange="gotoPage(this)">
               <option value = "http://domainname/#/rooms/1236?user=OfficeInvader">ATL 1 Office</option>
               <option value = "http://domainname/#/rooms/1235?user=OfficeInvader">ATL 2 Office</option>
               <option value = "http://domainname/#/rooms/1240?user=OfficeInvader">Destin 1 Office</option>
               <option value = "http://domainname/#/rooms/1239?user=OfficeInvader">Destin 2 Office</option>
             </select>
          </p>
       </fieldset>
    </form>

<script type="text/javascript">
function gotoPage(select){
    window.location = select.value;
}
</script>

Does jangouts have a tie in to html code so i could have the introductory name tie into the links? or would this need to be done in java?

**Comment by imobachgs** [comment]
Hi @cshar85,

I guess you could create an Angular directive which shows all the rooms and allows you to select one. You could have a look at [jh-signin-form directive](https://github.com/jangouts/jangouts/blob/8f24fdc0bbf9e1cc37134a20e0cb1d0b880dd1b7/src/app/components/user/jh-signin-form.directive.js) to get some inspiration.

**Comment by cshar85** [comment]
Awesome thanks! Ill go down that route.

**Comment by ancorgs** [comment]
I don't see this moving forward. So I will close the issue.
