### ISSUE TITLE
administring rooms is missing

### ISSUE THREAD

**Issue by eldemerdash** [jangouts/jangouts#219]
There is no admin for the video rooms and cannot destroy the room by any how of control? i see there is a variable to set beside "pin" which is "secret", is this enabled or not yet?

**Comment by ancorgs** [comment]
Well, Jangouts is basically a client for [Janus Gateway](http://janus.conf.meetecho.com/). Administration of the rooms or any other configuration aspect of the Janus Gateway instance is, at this moment, out of the scope of Jangouts.

You can check the documentation available at the Janus webpage (it's a very well documented project). But to answer your concrete question, you need to adjust the `/etc/janus/janus.plugin.videoroom.cfg` file (which is, by the way, mentioned in [the Jangouts README file](janus.plugin.videoroom.cfg)) and, very likely, restart Janus afterwards.

**Comment by ancorgs** [comment]
Closing the issue since, as mentioned, is out of our current scope. If you need more help, don't hesitate to visit the `#jangouts` channel on irc.freenode.net or [our Google Group](https://groups.google.com/d/forum/jangouts)
