### ISSUE TITLE
Jangouts looses connection to the gateway

### ISSUE THREAD

**Issue by OleksandrOrlov** [jangouts/jangouts#221]
Jangouts crashes for all the participants in the meeting. It happens randomly, but seems more likely while using screen sharing. 

Version 0.4.7

The following error message appears for all the participants:
![screenshot from 2018-04-13 10-36-59](https://user-images.githubusercontent.com/37581072/38924287-d9a07c58-42fc-11e8-8ca4-9a494e32c01a.png)

**Comment by ancorgs** [comment]
Yes, we have noticed that lately in the internal SUSE server. I need to reclaim my access to it (the admins changed something and my SSH cookie is not accepted anymore) and then debug what's going on there.

In other words, the internal SUSE server is likely not actively maintained right now, hence the failures. Not sure when will I have time to debug it, though.

**Comment by okurz** [comment]
I could reproduce the issue by staying in one room on my own and having screen sharing enabled. After 13 minutes the same message appeared.

**Comment by ancorgs** [comment]
These janus-gateway stability problems (not really a Jangouts issue) should be gone by now (since a long time ago, to be honest).
