### ISSUE TITLE
Disable audio and video in startup

### ISSUE THREAD

**Issue by maximzon** [jangouts/jangouts#222]
I've installed Janus on Ubuntu OS.
How can i disable audio and video on startup to decrease a bandwidth? 
Most of the time in the audio there are indiscriminate sounds, how can it be fixed ?
Often the audio channel of some users is disconnected. Ignore and unignore is the workaround but with 10+ users that makes it impossible to follow the discussion.

**Comment by ancorgs** [comment]
Kind of a duplicate of #80. Closing this in favor of the other.
