### ISSUE TITLE
No text chat

### ISSUE THREAD

**Issue by sunnybear** [jangouts/jangouts#223]
Fresh install on CentOS 7 via building from source janus, configuration

libsrtp version:           1.5.x
SSL/crypto library:        OpenSSL
DTLS set-timeout:          not available
DataChannels support:      yes
Recordings post-processor: no
TURN REST API client:      yes
Doxygen documentation:     no
Transports:
    REST (HTTP/HTTPS):     yes
    WebSockets:            yes
    RabbitMQ:              no
    MQTT:                  no
    Unix Sockets:          yes
Plugins:
    Echo Test:             yes
    Streaming:             yes
    Video Call:            yes
    SIP Gateway (Sofia):   no
    SIP Gateway (libre):   no
    NoSIP (RTP Bridge):    yes
    Audio Bridge:          yes
    Video Room:            yes
    Voice Mail:            yes
    Record&Play:           yes
    Text Room:             yes
    Lua Interpreter:       yes
Event handlers:
    Sample event handler:  yes
    RabbitMQ event handler:no
JavaScript modules:        no

Jangouts installed in folder, audio/video OK. But text chat is not working. In console
Data channel not open yet. Skipping

What additional info do you need to debug? Maybe some configuration is required?

**Comment by ancorgs** [comment]
Sorry. We overlooked this. It's so old now that I don't know if it's still relevant. Please feel free to reopen if that's the case.
