### ISSUE TITLE
Create a branch for the React/Redux version

### ISSUE THREAD

**Issue by imobachgs** [jangouts/jangouts#227]
Create a new branch, drop current code (keep docs, readme and so on) and use [create-react-app](https://github.com/facebook/create-react-app (or a similar alternative) to set up a React based application).

**Comment by dgdavid** [comment]
Done (commits 305591f33315bbef00e5dbfd7c9549a45f931022 and 66959633b9191b086b4f88873fd05c9e09e1ee09)
