### ISSUE TITLE
Alternative UI for lower CPU usage

### ISSUE THREAD

**Issue by ancorgs** [jangouts/jangouts#26]
Right now, the limiting factor for big meetings is the CPU usage needed to render all the videos in the clients. Bandwidth and CPU power on the server seems to not be a big issue. We should create alternative user interfaces less CPU hungry.

A first approach could be to only render the main video, keeping the thumbnails as audio-only.

We could need to investigate which situations produce the highest CPU consumption.

More elaborated solutions can be tried, like rendering video only for participants that are speaking and/or moving (with motion detection in the publisher side).

**Comment by bmwiedemann** [comment]
another option: only transmit/render a still image (e.g. I-frame) every few seconds for the small screens.
or allow to disable video for some participants.

btw: MPEG2 videos are encoded in a way that makes it easy+efficient to render 1/16 size versions of I-frames by just using the DC-values from the quantisation.

**Comment by ancorgs** [comment]
Partially implemented in https://github.com/jangouts/jangouts/commit/01cab15fded2c77bf37a6c97d2a788ad87954c71 which offers a button to reduce the number of rendered videos.

**Comment by ancorgs** [comment]
An working solution is already in master. We will need a couple of days to stabilize all the recent changes, but the bug can be considered as addressed. So closing.
