### ISSUE TITLE
Add logout action

### ISSUE THREAD

**Issue by imobachgs** [jangouts/jangouts#263]
Add a logout action which takes the user to the login screen again.

**Comment by dgdavid** [comment]
A first approach of the logout action has been implemented in #280. However, we should bear in mind

* To reset the whole state.
* To use a more react-router-dom to _navigate_ after performing an action (?). See https://github.com/jangouts/jangouts/pull/280#discussion_r378235854

**Comment by dgdavid** [comment]
> To reset the whole state.

See #282
