### ISSUE TITLE
Participants list takes too much space on small screens

### ISSUE THREAD

**Issue by cwh42** [jangouts/jangouts#28]
This is a full-screen window on my Laptop.
![jangouts](https://cloud.githubusercontent.com/assets/336868/8157413
/eb5775b2-1354-11e5-8d58-5fd12ba8ddf5.png)

**Comment by ancorgs** [comment]
We are aware. It's a consequence of the half-made revamp of the UI. @cyntss will resume the work on the UI in a couple of weeks.

**Comment by ancorgs** [comment]
This does not happen anymore with the new interface in master. Sure it has other problems since is not finished either, but at least this is fixed.
