### ISSUE TITLE
Firefox crashing when closing a shared window

### ISSUE THREAD

**Issue by imobach** [jangouts/jangouts#3]
If you close a window that you're sharing, Firefox just crashes. Confirmed with Firefox 37.0.2.

Thanks @bmwiedemann for reporting this issue.

**Comment by bmwiedemann** [comment]
Since this is actually a Firefox bug and not a problem in jangouts, I filed it at https://bugzilla.mozilla.org/show_bug.cgi?id=1164428

**Comment by imobach** [comment]
I experienced this issue in the past too. But it seems to work with Firefox 38.0.1. Anyway, I've updated the [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1164428) submitted by @bmwiedemann.

Anyway, when the window is closed, it stays as connected (#25).

**Comment by imobach** [comment]
Closing this issue as it seems that it works for 38.0.1 (and nightly builds).
