### ISSUE TITLE
Screen sharing does not work in Firefox

### ISSUE THREAD

**Issue by imobachgs** [jangouts/jangouts#303]
Screen sharing does not seem to work in Firefox. From the person who shares the screen, everything looks fine. But the rest will not see the corresponding video.

**Comment by ancorgs** [comment]
@imobachgs Isn't this the same than #324? I believe is the same and, thus, fixed by #341

**Comment by imobachgs** [comment]
Yes, most likely it is the same bug. I will reopen if needed. Thanks.
