### ISSUE TITLE
Basic chat rendering

### ISSUE THREAD

**Issue by imobachgs** [jangouts/jangouts#304]
Add support for basic things like:

- rendering images
- rendering URLs
- support for markdown-like style language
- support mentions (using `@`)

**Comment by dgdavid** [comment]
https://github.com/react-ninja/react-text-format could be and allied for this, but I'd prefer to avoid _lodash_ and similar dependencies when possible.

**Comment by dgdavid** [comment]
To support Markdown, maybe something like https://github.com/this-fifo/use-marked-hook

**Comment by dgdavid** [comment]
Another option could be https://github.com/milesj/interweave. Dependencies-free.

**Comment by ancorgs** [comment]
Interweave looks perfect for our purposes. See #317.

**Comment by ancorgs** [comment]
After merging #318 it will be possible to write bold, italics or strikeout text just using HTML marks. But I guess we also want to offer more convenient alternatives to achieve that basic formatting in the new Jangouts chat. My question is, what should we aim for?

1) When using plain text, I would say the traditional convention from the early days of Internet is using asterisks for bold text `I want *this* bold`. It's also kind of standard to strike through text with something like this `some ~strikethrough~ text`. In that context, underscore usually means italics.

2) But nowadays, markdown is becoming more and more popular. With markdown asterisks and underscore are equivalent and work like this: `this is _italic_ and *this too*. While this is __bold__, just **like this**`.

I personally prefer (1), it's more natural for me and more convenient for a chat. It's also the convention used by WhatApp, for example. But I'm not decided. What do others think?

**Comment by dgdavid** [comment]
As said in IRC, for the chat I prefer the first option.

**Comment by ancorgs** [comment]
Closed via #318
