### ISSUE TITLE
Rename the React based version branch

### ISSUE THREAD

**Issue by imobachgs** [jangouts/jangouts#313]
The name of the React based version sucks (sorry). We would like to rename it from `rewrite-using-react-redux` to just `react`.

**Comment by dgdavid** [comment]
Guys, now that we have merged #304, #319, and #323 seems to be a good moment for renaming the branch.

So, if you don't mind, please go ahead.

**Comment by imobachgs** [comment]
It is now called [react-redux](https://github.com/jangouts/jangouts/tree/react-redux).
