### ISSUE TITLE
Chat not auto-scrolling when new messages appear

### ISSUE THREAD

**Issue by Wurzelmann** [jangouts/jangouts#322]
I tried various branches of jangouts and noticed the chat is not auto-scrolling when new messages appear, except in the master branche.

Branches I tried, where this did not work:

- react/tailwindcss
- rewrite-using-react-redux

**Comment by ancorgs** [comment]
That's addressed at #318 (still not merged because I haven't found the time to implement the unit tests)

**Comment by ancorgs** [comment]
BTW, since you are checking branches... interested in contributing somehow? :wink:

**Comment by Wurzelmann** [comment]
Thanks for the heads-up! I'm checking branches, because I'm experimenting with different frontends for Janus right now. If I can contribute somewhere, I will! :-)

**Comment by dgdavid** [comment]
Just for the record

> Branches I tried, where this did not work:
>
> - react/tailwindcss
> - rewrite-using-react-redux

As you probably know, those branches still under development. It's being slower than we wish but ASAP I'll update the `rewrite-using-react-redux` with quite a lot changes on top of `react/tailwindcss` which, IMHO, improves the current status of the UI for the react rewrite.

So, stay tuned :)

Thanks a lot for give it a try.

**Comment by Wurzelmann** [comment]
> Just for the record
> 
> > Branches I tried, where this did not work:
> > 
> > * react/tailwindcss
> > * rewrite-using-react-redux
> 
> As you probably know, those branches still under development. It's being slower than we wish but ASAP I'll update the `rewrite-using-react-redux` with quite a lot changes on top of `react/tailwindcss` which, IMHO, improves the current status of the UI for the react rewrite.
> 
> So, stay tuned :)
> 
> Thanks a lot for give it a try.

Nice, thanks! I made a Frankenstein merge today between `rewrite-using-react-redux`, `react/tailwindcss` and `interweave scroll` just for testing and it worked great in a quick and dirty build and most important of all: the scroll auto-chat works fine. :-)

**Comment by dgdavid** [comment]
@Wurzelmann, friendly ping :)

Finally, yesterday we were able to go a step ahead[1] with the [`react-redux`](https://github.com/jangouts/jangouts/tree/react-redux) branch (yes, finally we renamed it :tada: ). Now, it's in better shape. So, if you still experimenting with Janus frontends, do you mind testing it again and provide your feedback?

Thanks!

---

[1] See https://github.com/jangouts/jangouts/pull/318, https://github.com/jangouts/jangouts/pull/319, https://github.com/jangouts/jangouts/pull/323, https://github.com/jangouts/jangouts/pull/327

**Comment by Wurzelmann** [comment]
Thanks for the heads-up, building and testing right now!

**Comment by Wurzelmann** [comment]
> @Wurzelmann, friendly ping :)
> 
> Finally, yesterday we were able to go a step ahead[1] with the [`react-redux`](https://github.com/jangouts/jangouts/tree/react-redux) branch (yes, finally we renamed it tada ). Now, it's in better shape. So, if you still experimenting with Janus frontends, do you mind testing it again and provide your feedback?
> 
> Thanks!
> 
> [1] See #318, #319, #320, #323, and #327

Feedback: interface looks very slick, I love the "hide chat" option, especially on mobile devices.

Bug: chat auto-scroll works as intended, but only until one hides the chat and opens it again. Then it is stuck at the top again and does not auto-scroll again.

**Comment by Wurzelmann** [comment]
> Bug: chat auto-scroll works as intended, but only until one hides the chat and opens it again. Then it is stuck at the top again and does not auto-scroll again.

slight correction: auto-scroll works again when I manually scroll to the latest message

**Comment by ancorgs** [comment]
> slight correction: auto-scroll works again when I manually scroll to the latest message

Yes. That's intentional. Auto-scroll only takes place when a new message arrives if you are already at the bottom of the chat. Otherwise it would be annoying when you have scrolled-up to read some older message.

The problem here is that "show chat" is not scrolling automatically to the bottom and/or restoring the viewpoint that was displayed when the chat was hidden.

Good catch!

**Comment by Wurzelmann** [comment]
> The problem here is that "show chat" is not scrolling automatically to the bottom and/or restoring the viewpoint that was displayed when the chat was hidden.
> 
> Good catch!

What about a button next to the chat which jumps to the latest message? This way, it is optional but would restore auto-scroll with a single click.

**Comment by dgdavid** [comment]
Thanks a lot, @Wurzelmann!

**Comment by Wurzelmann** [comment]
> Thanks a lot, @Wurzelmann!

Happy to help, my pleasure! I tried looking at the react code myself but did not know where to begin frankly, so at the moment, I guess this is all I can do.

Another feature request: would it be possible to add the current participants' count at the login like in the "classic" jangouts?

**Comment by ancorgs** [comment]
Ok. Added that point about the participants count to #329

**Comment by Wurzelmann** [comment]
Great, thank you.

**Comment by Wurzelmann** [comment]
I've got a few more bugs for this branche, should I just put them in here or open separate issues for them?

**Comment by dgdavid** [comment]
I'd prefer a new issue for each bug you found.

**Comment by Wurzelmann** [comment]
Okay, closing this one and opening up new ones, thank you.
