### ISSUE TITLE
Shared screens are not detected properly

### ISSUE THREAD

**Issue by imobachgs** [jangouts/jangouts#324]
While testing changes in #323, we detected that the shared screens were hidden.

* If you join a room where there is already a shared screen, you get the `video: true` property and it works just fine (you can see the shared screen).
* However, if the screen is shared after you have joined, you are not able to see the screen (the `video: true` is never set).

The problem was already there, but #323 made it evident.

**Comment by saket424** [comment]
I can replicate this issue. Any recommendations for fixing this important screen share issue ?

**Comment by ancorgs** [comment]
This happens only in the react-redux branch. Master is not affected.

**Comment by ancorgs** [comment]
Fixed by #341
