### ISSUE TITLE
Finish adaptation of login page

### ISSUE THREAD

**Issue by ancorgs** [jangouts/jangouts#329]
Some things to do as part of this:

- ~~Bring back current participants' count for each room~~. 
- ~~Removing notes about browser compatibility (we never update it)~~.
- ~~Rework slogan (the current one was just a proposal)~~.
- Bring back info about screen-sharing. -> Probably not needed anymore, at least not here.

**Comment by dgdavid** [comment]
> * Rework slogan (the current one was just a proposal).

This is the point where we should discuss about the logo, which was picked from 

https://github.com/jangouts/jangouts/blob/new_look/src/images/jangouts-logo.png

As you can see, 

* It's not an scalable (SVG) file, which actually isn't a problem, but it'd great to have such version.
* It includes the mentioned slogan.

**Comment by ancorgs** [comment]
Everything looks done by now.
