### ISSUE TITLE
[bug] [branch: react-redux] links in chat open in same tab

### ISSUE THREAD

**Issue by Wurzelmann** [jangouts/jangouts#330]
When opening links from the chat, by default they get opened in the same tab thus disconnecting yourself from the room.

**Comment by ancorgs** [comment]
Actually I implemented it like that intentionally, since I find web pages that open links in a new window to be very annoying. But after discussing it with @imobachgs and @dgdavid, I agree to change the current behavior to always use a new window, as implemented at #334.

**Comment by ancorgs** [comment]
Closed via #334
