### ISSUE TITLE
[bug] [branch: react-redux] no new chat notifications

### ISSUE THREAD

**Issue by Wurzelmann** [jangouts/jangouts#331]
Regardless if the chat is hidden or shown, there are no notifications about new messages (like the number of new messages next to the chat icon or small indicator like a coloured circle or something similar), which were part of the "classic" jangouts interface, if I'm not mistaken.

**Comment by joseivanlopez** [comment]
* In some cases, emojis are not correctly rendered.
* Emoji peeker is missing.

**Comment by joseivanlopez** [comment]
Some chat improvements were done in https://github.com/jangouts/jangouts/pull/383.

**Comment by ancorgs** [comment]
Now we have the counter for new (unread) chat messages. Thus, I'm closing this issue. @joseivanlopez feel free to open a separate one for the other things you mentioned in your comment, they are not related to the original scope of the issue.
