### ISSUE TITLE
Footer way too big on mobile phones

### ISSUE THREAD

**Issue by M-Stenzel** [jangouts/jangouts#354]
Hi,

thank you for the software.
When I open my jangouts page with a mobile phone (different browsers, e. g. Chrome, Firefox) the footer (SUSE 2015 version 0.5.0) is really big and that eats space for the actual content. Is it possible to create a mobile version?

Martin.
![jangouts_mobile](https://user-images.githubusercontent.com/76916440/156895379-37a8b35c-49a9-4ed4-9c24-df927a8c5fbb.jpg)

**Comment by ancorgs** [comment]
Jangouts interface is certainly not designed for mobile phones.

At some point we started a rewrite of the interface using react. See https://github.com/jangouts/jangouts/projects/1 That new interface was mobile-first (designed to work in mobile phones, tablets and PC). Unfortunately we never finished... although we are considering to try to finish it this summer.

**Comment by ancorgs** [comment]
The UI rewrite is finished and released in version 0.6.0. So this should not be a problem anymore.
