### ISSUE TITLE
Do not get remote videos after asking for permissions

### ISSUE THREAD

**Issue by imobachgs** [jangouts/jangouts#387]
It looks like Jangouts does not display remote videos after asking for mic/camera permissions. However, if it does not need to ask for those permissions, it works just fine.

**Comment by ancorgs** [comment]
I cannot reproduce this in my development environment.

**Comment by ancorgs** [comment]
We did a debugging session and looks like nobody reproduced this. I'm going to close it for now. We may re-open it if you observe that happening again.

**Comment by ancorgs** [comment]
Closing as WORKSFORME as commented.
