### ISSUE TITLE
Remember chat messages

### ISSUE THREAD

**Issue by joseivanlopez** [jangouts/jangouts#389]
When you leave a room, the list of messages is not recovered when you enter into the room again.

**Comment by ancorgs** [comment]
Actually I have always thought that is a weird historical behavior of Jangouts. I find the current behavior of the react branch (having the list of messages blank every time you re-enter the room) to be more natural.

**Comment by ancorgs** [comment]
Since @dgdavid seem to agree with my comment, I'm closing this.
