### ISSUE TITLE
Offer a button to (un)mute and enable/disable the video in the toolbar

### ISSUE THREAD

**Issue by imobachgs** [jangouts/jangouts#392]
If you want to unmute yourself, for instance, to say "goodbye" at the end of a call, it is hard to click on the "unmute" button because it is moving as the people are leaving the room. I would be good to have a button to (un)mute and enable/disable the video at the top bar.

**Comment by ancorgs** [comment]
Being worked at https://github.com/jangouts/jangouts/pull/400

**Comment by imobachgs** [comment]
Closed by #400.
