### ISSUE TITLE
Jangouts react-redux fails to load config.json if not in root context

### ISSUE THREAD

**Issue by Eierkopp** [jangouts/jangouts#426]
config.json is fetched as "/config.json" in config.js. This fails, when hosted behind some prefix.

    diff --git a/src/utils/config.js b/src/utils/config.js
    index 3fc15c6..cd2039c 100644
    --- a/src/utils/config.js
    +++ b/src/utils/config.js
    @@ -86,7 +86,7 @@ function parseConfig(text) {
      *  
      */
     export const fetchConfig = async () => {
    -  const response = await fetch('/config.json');
    +  const response = await fetch('config.json');
       if (response.ok) {
         return parseConfig(await response.text());
       } else {

**Comment by ancorgs** [comment]
Fixed by #428
