### ISSUE TITLE
npm install 

### ISSUE THREAD

**Issue by interfaith** [jangouts/jangouts#436]
N Could not resolve dependency:
npm WARN peer react@"^0.16.0" from better-docs@1.2.2
npm WARN node_modules/better-docs
npm WARN   dev better-docs@"1.2.2" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-dom@^0.16.0.

how to build it ?

**Comment by imobachgs** [comment]
Hi @interfaith,

It works for me. Which version of `node` and `npm` are you using?

PS: anyway, we should update many of our dependencies.

**Comment by interfaith** [comment]
node/npm spowage@teleden:~$ node -v
v20.5.1
spowage@teleden:~$ nodejs -v
v18.13.0
spowage@teleden:~$ npm -v
9.8.0

all good now
maybe via v 18
