### ISSUE TITLE
Add a test suite

### ISSUE THREAD

**Issue by imobachgs** [jangouts/jangouts#44]
Jangouts is getting bigger and bigger so, IMHO, we must build a test suite.

**Comment by ancorgs** [comment]
In my opinion we should have separate issues for unit tests (should be covered by #156) and end-to-end (integration) tests. I would aim for decent unit test coverage for milestone 0.5.0... probably leaving e2e tests for the next version.

**Comment by imobachgs** [comment]
We already have a test suite in the angular-2 branch (only unit tests).

**Comment by ancorgs** [comment]
We have some unit tests now, as part of the migration to React done in version 0.6.0.

It can of course be expanded over time, but I'm closing this because we indeed have a test suite now.
