### ISSUE TITLE
Deactivate local video channel when disabling video

### ISSUE THREAD

**Issue by ancorgs** [jangouts/jangouts#51]
In the past, the buttons for muting or disabling local video really disabled the corresponding channels of the stream locally. Now the channels remain activated but are not sent to the other peers. That is great for audio because it allowed us to implement https://github.com/jangouts/jangouts/issues/27. But for video is not that great. The user can still manage to see their own video and may think that it's being transmitted. So disabling the local video channel in addition to stop sending it would give us the best of both worlds and should be easy to implement with some git archeology.

**Comment by jreidinger** [comment]
fixed by #90
