### ISSUE TITLE
Option to disable the notification

### ISSUE THREAD

**Issue by nilxam** [jangouts/jangouts#69]
Once you're muted but jangout supposed you are speaking then it will notice you by text and audio, we should have an option can disable it.

**Comment by vuntz** [comment]
The "ding" sound is actually quite annoying after a while :-)

**Comment by ancorgs** [comment]
The "ding" was carefully crafted to be annoying. :wink:

**Comment by jsuchome** [comment]
It's problematic especially when you are using different application (like mumble) for audio.

**Comment by jreidinger** [comment]
I would try to implement it ( no permission to assign to me )

**Comment by jreidinger** [comment]
fixed by #87
