### ISSUE TITLE
can't copy text from chat with mouse

### ISSUE THREAD

**Issue by aspiers** [jangouts/jangouts#71]
If I try to highlight text from the chat pane in order to copy and paste, it just drags the pane around.

**Comment by ancorgs** [comment]
We could add a dragging handler so only clicking on it (and not in any point of the frame) would trigger the dragging event. That's trivial from the implementation POV. We just need a good idea on how it should look like. Something like the titlebar of a window? Something that appears on mouse over? Some kind of collapsed tab?... Mockups are welcome.

**Comment by ancorgs** [comment]
After discussing alternatives with @mdeniz, @ChrisBr and @cwh42, it was decided that the best approach would be having two modes (with a button to toggle), one with all the dragging and resizing blocked and another one to play around with the layout.

**Comment by ChrisBr** [comment]
@mdeniz self assigned to me because it's related to #74! JFYI
