### ISSUE TITLE
Can't unmute when I got muted by someone else

### ISSUE THREAD

**Issue by vuntz** [jangouts/jangouts#73]
We had a call yesterday, and somebody muted somebody else. That person was not able to speak anymore as there was no way to unmute him...

**Comment by ancorgs** [comment]
That should for sure not happen. You cannot unmute others (that's on purpose) but you can always unmute yourself, no matter who muted you.

**Comment by ancorgs** [comment]
@vuntz still having this issue? I'm cleaning the issue list and this looks like a nice candidate to be closed :wink:

**Comment by ancorgs** [comment]
Anyway, I will close this for the sake of cleanup and feel free to reopen it.

**Comment by vuntz** [comment]
> @vuntz still having this issue? I'm cleaning the issue list and this looks like a nice candidate to be closed

We'll check next time we use jangouts :-)
