### ISSUE TITLE
layout changes don't persist

### ISSUE THREAD

**Issue by aspiers** [jangouts/jangouts#74]
If I rearrange the position/size of the panes on the meeting page, the new layout gets lost when I reload the page.  This should be persisted either locally via cookies, or server-side per user account.

**Comment by ancorgs** [comment]
Actually, this does not work always. The `gridster-resized` is only triggered once (you really cannot trust angular-gridster events), so in many situations the last layout is not properly saved.

I would prefer to save it when quitting the "resize mode", even displaying a notification about it having been saved (without bell, please :wink:).

**Comment by ChrisBr** [comment]
@ancorgs okay!

**Comment by ChrisBr** [comment]
Fixed with #99
