### ISSUE TITLE
Bookmarkable username and room

### ISSUE THREAD

**Issue by ancorgs** [jangouts/jangouts#9]
It should be possible to create a bookmark for the current username and room selections, so entering the same room everyday (or several times per day) is more straightforward.

**Comment by ChrisBr** [comment]
@ancorgs @imobach Any rough idea how we could implement that? I'd simply go with URL parameters e.g. ```/:room/:user``` and then login the user into the room. Sounds that reasonable?

**Comment by ancorgs** [comment]
@ChrisBr yes, that's the plan. I would start the implementation googling for "angular routes"

**Comment by ChrisBr** [comment]
@ancorgs Alright, will have a loot at it on the weekend

**Comment by imobach** [comment]
@ChrisBr @ancorgs We're using [ui-router](https://github.com/angular-ui/ui-router) which is quite powerful.
